@startuml

start
:Начало;
:Вход в систему;
:Ввод данных;
if (Есть ли пациента в базе данных?) then (да)

else (нет)
  :Регистрация;

endif
  :Запись на свободное время;
    :Вход в систему;
:Конец;
@enduml